# A new Azure Devops project will be created with the following configuration values.
# You can, but don't have to edit these
ado_project_name: "HendrikBruinsma"
ado_repository_name: "HendrikBruinsmaRepo"

# Update these values before running the bootstrap script

ado_url: "https://dev.azure.com/xpirit"  # e.g "https://dev.azure.com/your-org"

github_org: "cloudcosmonaut"
target_github_repo_name: "migrated-repo"